on:
  push:
    branches:
      - main
      - develop
    paths:
      - "app/**"
  workflow_dispatch:

jobs:
  build-and-push:
    uses: ./.github/workflows/build.yml
    with:
      branch: ${{ github.ref_name }}
      environment: ${{ github.ref_name == 'main' && 'production' || 'development' }}
      docker_repo: ${{ vars.DOCKER_REPO }}
      username: ${{ vars.DOCKER_USERNAME }}
      service: app
    secrets:
      password: ${{ secrets.DOCKER_PASSWORD }}

  deploy:
    uses: ./.github/workflows/deploy.yml
    needs: build-and-push
    with:
      environment: ${{ github.ref_name == 'main' && 'production' || 'development' }}
      docker_repo: ${{ vars.DOCKER_REPO }}
      service: app
    secrets:
      SERVER_IP: ${{ secrets.SERVER_IP }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      DB_USERNAME: ${{ secrets.DB_USERNAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      JWT_PUBLIC_KEY: ${{ secrets.JWT_PUBLIC_KEY }}
