on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    uses: ./.github/workflows/build.yml
    with:
      branch: feature/client_auth
      docker_repo: ${{ vars.DOCKER_REPO }}
      service: auth
    secrets:
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

  deploy:
    uses: ./.github/workflows/deploy-auth.yml
    needs: build-and-push
    with:
      docker_repo: ${{ vars.DOCKER_REPO }}
    secrets:
      SERVER_IP: ${{ secrets.SERVER_IP }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      DB_USERNAME: ${{ secrets.AUTH_DATABASE_USER }}
      DB_PASSWORD: ${{ secrets.AUTH_DATABASE_PASSWORD }}
      DATABASE_HOST: ${{ secrets.AUTH_DATABASE_HOST }}
      DATABASE_PORT: ${{ secrets.AUTH_DATABASE_PORT }}
      DATABASE_NAME: ${{ secrets.AUTH_DATABASE_NAME }}
      JWT_PRIVATE_KEY: ${{ secrets.JWT_PRIVATE_KEY }}
      JWT_PUBLIC_KEY: ${{ vars.JWT_PUBLIC_KEY }}
      JWT_REFRESH_TOKEN_EXPIRATION_MS: ${{ secrets.JWT_ACCESS_TOKEN_EXPIRATION_MS }}
      JWT_ACCESS_TOKEN_EXPIRATION_MS: ${{ secrets.JWT_REFRESH_TOKEN_EXPIRATION_MS }}
