on:
  push:
    branches:
      - develop
    paths:
      - "app/**"
  workflow_dispatch:

jobs:
  build-and-push:
    uses: ./.github/workflows/build.yml
    with:
      branch: develop
      docker_repo: ${{ vars.DOCKER_REPO }}
      username: ${{ vars.DOCKER_USERNAME }}
      service: app-dev
    secrets:
      password: ${{ secrets.DOCKER_PASSWORD }}

  deploy:
    uses: ./.github/workflows/deploy.yml
    needs: build-and-push
    with:
      docker_repo: ${{ vars.DOCKER_REPO }}
      service: app-dev
      service_port: 5000
      app_url: https://dev.freed.itayoshri.com
    secrets:
      SERVER_IP: ${{ secrets.SERVER_IP }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      DB_USERNAME: ${{ secrets.DB_USERNAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      JWT_PUBLIC_KEY: ${{ secrets.JWT_PUBLIC_KEY }}
